# =========================================================
# 🧠 personal-assistant-backend-fly
# Production-ready Fly.io config for a multi-region Go API
# =========================================================
app = "personal-assistant-backend-fly"
primary_region = "sjc"

[build]
  # Your Dockerfile handles Go build
  # (no changes needed)

[deploy]
  # 🟢 Enable rolling deploys across ALL regions
  # This ensures every running machine (in all regions) gets replaced.
  strategy = "rolling"

  # Optional: Run swag docs before release (disabled for speed)
  # release_command = "swag init -g main.go -o docs"

# =========================================================
# 🌐 HTTP Service Configuration
# =========================================================
[http_service]
  internal_port = 8080
  force_https = true

  # Keep both regions warm (no cold starts)
  auto_stop_machines = false
  auto_start_machines = true

  # Ensure both SJC and EWR always have an active instance
  min_machines_running = 2

  # Rolling deploy safety: restart one region at a time
  max_concurrent_startups = 1

  processes = ["app"]

# =========================================================
# ⚙️ VM Resources (per machine)
# =========================================================
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# =========================================================
# 🌎 Regional Deployment
# =========================================================
# Fly will deploy to both SJC (primary) and EWR (secondary)
# because you already have machines in both regions.
#
# You can confirm this mapping via:
#   fly regions list
#
# If a new region is ever added manually, Fly will also
# update those on the next deploy.
# =========================================================
