# fly.toml app configuration file for personal-assistant-backend-fly
# Generated and enhanced for automatic Swagger updates
#
# See https://fly.io/docs/reference/configuration/ for full options
#

app = 'personal-assistant-backend-fly'
primary_region = 'sjc'

[build]
  # Ensure swag CLI is available inside your image (if not already, add to Dockerfile)
  # Example: RUN go install github.com/swaggo/swag/cmd/swag@latest

[deploy]
  # ✅ Automatically regenerate Swagger docs before deployment
  # release_command = "swag init -g main.go -o docs"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
