basePath: /
definitions:
  handlers.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  handlers.loginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.signupReq:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        maxLength: 128
        minLength: 8
        type: string
      phone_number:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  models.AuthCheckResponse:
    properties:
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.AuthWithTokensResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.Chat:
    properties:
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  models.ChatCreateResponse:
    properties:
      chat:
        $ref: '#/definitions/models.Chat'
    type: object
  models.ChatListResponse:
    properties:
      chats:
        items:
          $ref: '#/definitions/models.Chat'
        type: array
    type: object
  models.CreateChatReq:
    properties:
      title:
        maxLength: 120
        type: string
    type: object
  models.Message:
    properties:
      chat_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      role:
        description: '"user" or "assistant"'
        type: string
    type: object
  models.MessageResponse:
    properties:
      assistant_message:
        $ref: '#/definitions/models.Message'
      user_message:
        $ref: '#/definitions/models.Message'
    type: object
  models.SendMessageReq:
    properties:
      content:
        type: string
    required:
    - content
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
info:
  contact:
    email: jordana.urbaez@gmail.com
    name: Jordan Urbaez
  description: REST API for authentication, user management, and assistant chat features.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Personal Assistant Backend API
  version: "1.0"
paths:
  /auth:
    get:
      description: Validates the user's access token and returns their account information
        if still logged in. This endpoint does not issue new tokens.
      produces:
      - application/json
      responses:
        "200":
          description: Valid token and user info (no tokens returned)
          schema:
            $ref: '#/definitions/models.AuthCheckResponse'
        "401":
          description: Invalid or expired token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Check user session (Auth validation)
      tags:
      - Auth
  /chats:
    get:
      description: Returns all chat sessions created by the logged-in user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ChatListResponse'
        "500":
          description: Database error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List all chats for current user
      tags:
      - Chats
    post:
      consumes:
      - application/json
      description: Creates a blank chat session for the logged-in user. Optionally
        accepts a title.
      parameters:
      - description: Optional chat title
        in: body
        name: payload
        schema:
          $ref: '#/definitions/models.CreateChatReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ChatCreateResponse'
        "400":
          description: Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new chat
      tags:
      - Chats
  /chats/{chat_id}/messages:
    get:
      description: Returns the full conversation history for a given chat ID.
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Message'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Chat not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all messages in a chat
      tags:
      - Chats
    post:
      consumes:
      - application/json
      description: Sends a message to a chat. The last 20 messages are sent as context
        to the AI model.
      parameters:
      - description: Chat ID
        in: path
        name: chat_id
        required: true
        type: string
      - description: User message content
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.SendMessageReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Chat not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database or model error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Send a message in a chat and get AI response
      tags:
      - Chats
  /greet:
    get:
      consumes:
      - application/json
      description: Returns a greeting using query parameters `first` and `last`.
      parameters:
      - description: First name
        in: query
        name: first
        required: true
        type: string
      - description: Last name
        in: query
        name: last
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful greeting
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Missing first or last name
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Greet API to greet user
      tags:
      - Misc
  /hello:
    get:
      description: Returns a greeting message. If no name is provided, defaults to
        "World".
      parameters:
      - description: Name to greet
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Greeting message
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Simple hello endpoint
      tags:
      - Misc
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with email and password, returning account
        info with JWT access and refresh tokens.
      parameters:
      - description: User login credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.loginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Authenticated user with access and refresh tokens
          schema:
            $ref: '#/definitions/models.AuthWithTokensResponse'
        "400":
          description: Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database or token generation error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login a user
      tags:
      - Auth
  /me:
    get:
      description: Returns the authenticated user's ID extracted from the JWT access
        token.
      produces:
      - application/json
      responses:
        "200":
          description: User ID returned successfully
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized or missing user ID
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get current user info
      tags:
      - Misc
  /signup:
    post:
      consumes:
      - application/json
      description: Creates a new user account in PostgreSQL and returns account info
        with JWT access + refresh tokens.
      parameters:
      - description: User signup data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.signupReq'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully with access and refresh tokens
          schema:
            $ref: '#/definitions/models.AuthWithTokensResponse'
        "400":
          description: Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Email already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database or hashing error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
  /token/refresh:
    post:
      consumes:
      - application/json
      description: Takes a valid refresh token and issues a new access token. The
        refresh token remains the same.
      parameters:
      - description: Refresh token payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: New access token issued
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid payload
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Invalid or expired refresh token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to generate new access token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh access token
      tags:
      - Auth
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
